export BUILT_PRODUCTS_DIR="/Users/alexleffelman/Library/Developer/Xcode/DerivedData/i2048-gljchvrffoiahddqoobfkbflrgsu/Build/Products/Debug-iphoneos"
export CURRENT_ARCH="arm64"
export OBJECT_FILE_DIR_normal="/Users/alexleffelman/Library/Developer/Xcode/DerivedData/i2048-gljchvrffoiahddqoobfkbflrgsu/Build/Intermediates/i2048.build/Debug-iphoneos/i2048.build/Objects-normal"
export OBJROOT="/Users/alexleffelman/Library/Developer/Xcode/DerivedData/i2048-gljchvrffoiahddqoobfkbflrgsu/Build/Intermediates"
export SRCROOT="/Users/alexleffelman/Dropbox/Code/i2048"
