export BUILT_PRODUCTS_DIR="/Users/alexleffelman/Library/Developer/Xcode/DerivedData/i2048-gljchvrffoiahddqoobfkbflrgsu/Build/Products/Debug-iphonesimulator"
export CURRENT_ARCH="i386"
export OBJECT_FILE_DIR_normal="/Users/alexleffelman/Library/Developer/Xcode/DerivedData/i2048-gljchvrffoiahddqoobfkbflrgsu/Build/Intermediates/i2048.build/Debug-iphonesimulator/i2048.build/Objects-normal"
export OBJROOT="/Users/alexleffelman/Library/Developer/Xcode/DerivedData/i2048-gljchvrffoiahddqoobfkbflrgsu/Build/Intermediates"
export SRCROOT="/Users/alexleffelman/Dropbox/Code/i2048"
